"""
A3 -- Clifford lattice horizon: the manifestly-reversible version of the
computational black hole.

Build a horizon in a 2D Clifford circuit:
  - 2D grid (LxL qubits, default 9x9 = 81)
  - Each step: a brick-wall layer of random 2-qubit Clifford gates
  - "Horizon" = circular region of radius r_h around the lattice centre
  - Inside the horizon: reset each qubit to |0> with probability p per step
    (the analog of the reservoir's leak/damping; information is genuinely
    destroyed because the reset traces out the qubit and replaces it with a
    fresh |0>)

The substrate is manifestly reversible OUTSIDE the horizon (pure Clifford
unitaries) and dissipative INSIDE (reset events). This is the cleanest
analog of the §7 reversible/dissipative split: the surrounding "exterior" is
unitary CAI-like, the "interior" is the dissipative-attenuation horizon.

Two tests:

Phase 1 -- time-resolved entropy of the horizon region.
  Initialize the lattice in a random Clifford scrambled state.
  Run T steps of (unitary brick wall + horizon erasure).
  Measure S(horizon, t).
  Pure unitary baseline (p=0): saturates near min(|H|, N-|H|) (Page bound).
  Dissipative horizon (p > 0): rises then falls -- entanglement with the
  exterior is built up by gates then destroyed by erasure.
  This is the Page curve generated BY THE HORIZON itself (rather than by a
  standalone scrambler, as in Test 3).

Phase 2 -- Clausius family.
  Sweep (r_h, p). For each, run long enough to reach steady state. Measure
  S_steady, the late-time time-averaged entropy of the horizon region.
  Plot S_steady vs A = 2*pi*r_h (boundary) and vs V = pi*r_h^2 (volume).
    Area law S_steady ~ A  with universal slope => Clausius can hold.
    Volume law S_steady ~ V                     => area-law fails.

Reuses the entanglement-entropy infrastructure from cwf_pagecurve.py
(stabilizer-rank entropy in symplectic GF(2)).
"""

import json, os, sys, time
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import stim

# import entropy machinery
sys.path.insert(0, os.path.dirname(__file__) or ".")
from cwf_pagecurve import gf2_rank, stabilizer_matrix, entropy_region

L = 9
N_QUBITS = L * L

def grid_idx():
    return {(i, j): i * L + j for i in range(L) for j in range(L)}

def horizon_qubits(idx, r_h):
    cx = cy = L / 2 - 0.5  # centre between grid cells
    return [q for (i, j), q in idx.items()
            if np.sqrt((i - cx) ** 2 + (j - cy) ** 2) < r_h]

def brick_wall_layers(idx):
    """Four sub-layers, cycled to make a brick-wall in 2D.
    Each sub-layer is a list of disjoint NN pairs."""
    H_even = [(idx[i, j], idx[i, j + 1])
              for i in range(L) for j in range(0, L - 1, 2)]
    H_odd  = [(idx[i, j], idx[i, j + 1])
              for i in range(L) for j in range(1, L - 1, 2)]
    V_even = [(idx[i, j], idx[i + 1, j])
              for j in range(L) for i in range(0, L - 1, 2)]
    V_odd  = [(idx[i, j], idx[i + 1, j])
              for j in range(L) for i in range(1, L - 1, 2)]
    return [H_even, H_odd, V_even, V_odd]


def run_horizon(r_h, p, T=120, init_steps=40, seed=0, measure_every=1):
    """Run one trajectory; return S_horizon vs time (incl. t=0)."""
    idx = grid_idx()
    horizon = horizon_qubits(idx, r_h)
    layers = brick_wall_layers(idx)
    rng = np.random.default_rng(seed)
    sim = stim.TableauSimulator(seed=int(seed))

    # ---- initial scrambling ----
    for d in range(init_steps):
        layer = layers[d % 4]
        for (a, b) in layer:
            t = stim.Tableau.random(2)
            sim.do_tableau(t, [a, b])

    # ---- measure initial S ----
    X, Z = stabilizer_matrix(sim, N_QUBITS)
    S0 = entropy_region(X, Z, horizon, N_QUBITS)
    S_t = [S0]

    # ---- time evolution ----
    for t in range(T):
        layer = layers[t % 4]
        for (a, b) in layer:
            tab = stim.Tableau.random(2)
            sim.do_tableau(tab, [a, b])
        # horizon erasure: reset each interior qubit with prob p
        for q in horizon:
            if rng.random() < p:
                sim.reset(q)
        if (t + 1) % measure_every == 0:
            X, Z = stabilizer_matrix(sim, N_QUBITS)
            S = entropy_region(X, Z, horizon, N_QUBITS)
            S_t.append(S)
    return np.array(S_t), len(horizon)


def run_avg(r_h, p, T=120, seeds=6, **kw):
    """Average S(t) over seeds; also return |horizon|."""
    runs = [run_horizon(r_h, p, T=T, seed=10 + s, **kw) for s in range(seeds)]
    S_arr = np.array([r[0] for r in runs])
    n_int = runs[0][1]
    return S_arr.mean(axis=0), S_arr.std(axis=0), n_int


# ---------------------------------------------------------------- Phase 1
def phase1():
    print(f"Phase 1: time-resolved S(horizon, t) on {L}x{L} Clifford lattice")
    r_h_test = 2.5
    ps = [0.0, 0.1, 0.3, 0.5, 1.0]
    T = 120
    curves = {}
    t0 = time.time()
    for p in ps:
        Smean, Sstd, n_int = run_avg(r_h_test, p, T=T, seeds=6)
        curves[p] = dict(S_mean=Smean.tolist(), S_std=Sstd.tolist(),
                        n_interior=n_int)
        print(f"  r_h={r_h_test}  p={p}  |interior|={n_int}  "
              f"S0={Smean[0]:.2f}  Speak={Smean.max():.2f}  "
              f"Sfinal={Smean[-1]:.2f}  (over {len(Smean)-1} steps)")
    print(f"  phase 1 took {time.time()-t0:.0f}s\n")
    return dict(r_h=r_h_test, T=T, ps=ps, curves=curves, n_interior=n_int)


# ---------------------------------------------------------------- Phase 2
def phase2():
    print(f"Phase 2: Clausius family sweep on {L}x{L} Clifford lattice")
    r_hs = [1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
    ps = [0.05, 0.15, 0.30, 0.50, 0.80]
    T = 100
    seeds = 6
    settle = 50    # take steady-state average over last (T - settle) steps
    rows = []
    t0 = time.time()
    for r_h in r_hs:
        for p in ps:
            Smean, Sstd, n_int = run_avg(r_h, p, T=T, seeds=seeds)
            S_steady = float(np.mean(Smean[settle:]))
            S_steady_std = float(np.std(Smean[settle:]))
            S_peak = float(np.max(Smean))
            A = 2 * np.pi * r_h
            Vol = np.pi * r_h ** 2
            rows.append(dict(r_h=r_h, p=p, A=A, V=Vol, n_interior=n_int,
                            S_peak=S_peak,
                            S_steady=S_steady,
                            S_steady_std=S_steady_std))
            print(f"  r_h={r_h:.1f}  p={p:.2f}  |int|={n_int:3d}  "
                  f"A={A:5.2f} V={Vol:5.2f}  "
                  f"S_steady={S_steady:6.2f}+-{S_steady_std:4.2f}  S_peak={S_peak:6.2f}")
    print(f"  phase 2 took {time.time()-t0:.0f}s")

    # Analyze: does S_steady fit area (S = c_A * A) or volume (S = c_V * V)?
    A = np.array([r["A"] for r in rows])
    V = np.array([r["V"] for r in rows])
    S = np.array([r["S_steady"] for r in rows])
    # log-log fit S vs A and S vs V
    good = S > 0.5
    if good.sum() >= 3:
        a_slope, a_int = np.polyfit(np.log(A[good]), np.log(S[good]), 1)
        v_slope, v_int = np.polyfit(np.log(V[good]), np.log(S[good]), 1)
        # also try linear (S = c * A vs S = c * V)
        cA = float(np.sum(S * A) / np.sum(A * A))
        cV = float(np.sum(S * V) / np.sum(V * V))
        rA = float(1 - np.sum((S - cA * A) ** 2) / np.sum((S - S.mean()) ** 2))
        rV = float(1 - np.sum((S - cV * V) ** 2) / np.sum((S - S.mean()) ** 2))
        print(f"\n  log-log fits (only S > 0.5):")
        print(f"    S ~ A^{a_slope:+.2f}     S ~ V^{v_slope:+.2f}")
        print(f"  linear fits:")
        print(f"    S = {cA:.3f} * A   R^2 = {rA:+.3f}")
        print(f"    S = {cV:.3f} * V   R^2 = {rV:+.3f}")
    else:
        a_slope = v_slope = float("nan")
        cA = cV = rA = rV = float("nan")

    # Per-p universality of S_steady / A (the Clausius coefficient)
    print(f"\n  per-p universality of S_steady / A:")
    for p in ps:
        e = [r["S_steady"] / r["A"] for r in rows if r["p"] == p and r["S_steady"] > 0.5]
        if e:
            print(f"    p={p:.2f}: S/A median={np.median(e):.3f}  range "
                  f"[{min(e):.3f}, {max(e):.3f}]  (n={len(e)})")

    # Check universality across (r_h, p) -- if S/A is constant for all rows,
    # area-law holds. We compute the CV of S/A across all rows with S>0.5.
    SA = S[good] / A[good]
    SV = S[good] / V[good]
    cv_SA = float(np.std(SA) / (abs(np.mean(SA)) + 1e-12))
    cv_SV = float(np.std(SV) / (abs(np.mean(SV)) + 1e-12))
    print(f"\n  cross-family CV (lower = more universal):")
    print(f"    CV(S/A) = {cv_SA:.3f}        CV(S/V) = {cv_SV:.3f}")

    if cv_SA < 0.20 and rA > 0.85:
        verdict = "AREA-LAW (S/A ~ universal)"
    elif cv_SV < 0.20 and rV > 0.85:
        verdict = "VOLUME-LAW (S/V ~ universal)"
    elif rA > rV:
        verdict = "PARTIAL AREA-LAW (S ~ A but not universal)"
    elif rV > rA:
        verdict = "PARTIAL VOLUME-LAW"
    else:
        verdict = "NO CLEAN SCALING"
    print(f"\n  VERDICT: {verdict}")

    return dict(L=L, N=N_QUBITS, T=T, seeds=seeds, r_hs=r_hs, ps=ps,
                rows=rows, area_slope=a_slope, volume_slope=v_slope,
                cA=cA, cV=cV, rA=rA, rV=rV, cv_SA=cv_SA, cv_SV=cv_SV,
                verdict=verdict)


# ---------------------------------------------------------------- main
def main():
    print(f"A3 -- Clifford lattice horizon  (L={L}, N={N_QUBITS} qubits)\n")
    p1 = phase1()
    p2 = phase2()

    # save
    out = os.path.join(os.path.dirname(__file__) or ".", "results.json")
    r_all = json.load(open(out)) if os.path.exists(out) else {}
    r_all["A3_clifford_horizon"] = dict(
        L=L, N=N_QUBITS, init_steps=40,
        phase1=p1, phase2=p2,
    )
    json.dump(r_all, open(out, "w"), indent=2)

    # ---- plots ---------------------------------------------------------
    fig = plt.figure(figsize=(15.5, 9.5))
    gs = fig.add_gridspec(2, 3, hspace=0.32, wspace=0.30)
    ax_p1   = fig.add_subplot(gs[0, 0])
    ax_p1l  = fig.add_subplot(gs[0, 1])
    ax_decay= fig.add_subplot(gs[0, 2])
    ax_a    = fig.add_subplot(gs[1, 0])
    ax_v    = fig.add_subplot(gs[1, 1])
    ax_pp   = fig.add_subplot(gs[1, 2])

    # (a) Phase 1: S(t) curves for various p
    colors = plt.cm.viridis(np.linspace(0.05, 0.85, len(p1["ps"])))
    for p, col in zip(p1["ps"], colors):
        c = p1["curves"][p]
        S = np.array(c["S_mean"]); sd = np.array(c["S_std"])
        ts = np.arange(len(S))
        ax_p1.plot(ts, S, "-", color=col, lw=1.5, label=f"p={p}")
        ax_p1.fill_between(ts, S - sd, S + sd, color=col, alpha=0.15)
    ax_p1.axhline(min(p1["n_interior"], N_QUBITS - p1["n_interior"]),
                  color="k", ls=":", lw=0.6, label="Page bound (unitary)")
    ax_p1.set_xlabel("time step")
    ax_p1.set_ylabel(r"$S$(horizon interior)  [bits]")
    ax_p1.set_title(f"(a) Page curve from horizon  "
                    f"($r_h$={p1['r_h']}, $|H|$={p1['n_interior']})")
    ax_p1.legend(fontsize=8); ax_p1.grid(alpha=0.3)

    # (b) Phase 1 log-y to see decay
    for p, col in zip(p1["ps"], colors):
        if p == 0.0: continue
        c = p1["curves"][p]
        S = np.array(c["S_mean"]); ts = np.arange(len(S))
        ax_p1l.semilogy(ts, S + 0.1, "-", color=col, lw=1.5, label=f"p={p}")
    ax_p1l.set_xlabel("time step"); ax_p1l.set_ylabel(r"$S$ (log)")
    ax_p1l.set_title("(b) Same, log-y")
    ax_p1l.legend(fontsize=8); ax_p1l.grid(alpha=0.3, which="both")

    # (c) S_steady vs p, for various r_h
    rh_colors = plt.cm.plasma(np.linspace(0.1, 0.85, len(p2["r_hs"])))
    for r_h, col in zip(p2["r_hs"], rh_colors):
        rows = [r for r in p2["rows"] if r["r_h"] == r_h]
        ax_decay.plot([r["p"] for r in rows],
                      [r["S_steady"] for r in rows],
                      "o-", color=col, lw=1.5, ms=5, label=f"r_h={r_h}")
    ax_decay.set_xlabel("erasure prob $p$")
    ax_decay.set_ylabel(r"$S_{\rm steady}$  [bits]")
    ax_decay.set_title("(c) Steady-state $S$ vs erasure rate")
    ax_decay.legend(fontsize=8); ax_decay.grid(alpha=0.3)

    # (d) S_steady vs A (boundary length)
    p_colors = plt.cm.viridis(np.linspace(0.1, 0.85, len(p2["ps"])))
    for p, col in zip(p2["ps"], p_colors):
        rows = [r for r in p2["rows"] if r["p"] == p]
        ax_a.plot([r["A"] for r in rows], [r["S_steady"] for r in rows],
                  "o-", color=col, lw=1.5, ms=5, label=f"p={p}")
    A_lin = np.linspace(0.1, max(r["A"] for r in p2["rows"]) * 1.05, 30)
    ax_a.plot(A_lin, p2["cA"] * A_lin, "k--", alpha=0.5,
              label=f"$S={p2['cA']:.2f}A$ ($R^2$={p2['rA']:+.2f})")
    ax_a.set_xlabel(r"area $A = 2\pi r_h$ (boundary length)")
    ax_a.set_ylabel(r"$S_{\rm steady}$  [bits]")
    ax_a.set_title(f"(d) $S$ vs boundary area  -- area law? CV={p2['cv_SA']:.2f}")
    ax_a.legend(fontsize=8); ax_a.grid(alpha=0.3)

    # (e) S_steady vs V (interior volume)
    for p, col in zip(p2["ps"], p_colors):
        rows = [r for r in p2["rows"] if r["p"] == p]
        ax_v.plot([r["V"] for r in rows], [r["S_steady"] for r in rows],
                  "o-", color=col, lw=1.5, ms=5, label=f"p={p}")
    V_lin = np.linspace(0.1, max(r["V"] for r in p2["rows"]) * 1.05, 30)
    ax_v.plot(V_lin, p2["cV"] * V_lin, "k--", alpha=0.5,
              label=f"$S={p2['cV']:.2f}V$ ($R^2$={p2['rV']:+.2f})")
    ax_v.set_xlabel(r"interior volume $V = \pi r_h^2$")
    ax_v.set_ylabel(r"$S_{\rm steady}$  [bits]")
    ax_v.set_title(f"(e) $S$ vs interior volume  -- volume law? CV={p2['cv_SV']:.2f}")
    ax_v.legend(fontsize=8); ax_v.grid(alpha=0.3)

    # (f) S_steady/A and S_steady/V across (r_h, p) -- universality
    ax_pp.boxplot(
        [[r["S_steady"]/r["A"] for r in p2["rows"] if r["p"] == p]
         for p in p2["ps"]],
        positions=np.arange(len(p2["ps"])) - 0.18, widths=0.3, patch_artist=True,
        boxprops=dict(facecolor="C0", alpha=0.5))
    ax_pp.boxplot(
        [[r["S_steady"]/r["V"] for r in p2["rows"] if r["p"] == p]
         for p in p2["ps"]],
        positions=np.arange(len(p2["ps"])) + 0.18, widths=0.3, patch_artist=True,
        boxprops=dict(facecolor="C1", alpha=0.5))
    ax_pp.set_xticks(np.arange(len(p2["ps"])))
    ax_pp.set_xticklabels([f"{p}" for p in p2["ps"]])
    ax_pp.set_xlabel("erasure prob $p$")
    ax_pp.set_ylabel(r"$S_{\rm steady}/A$  (blue)   /    $S_{\rm steady}/V$  (orange)")
    ax_pp.set_title("(f) Per-p box plots: universality test")
    ax_pp.grid(alpha=0.3, axis="y")

    fig.suptitle(f"A3: Clifford lattice horizon  ({L}x{L} qubits)  -- "
                 f"{p2['verdict']}", fontsize=11.5)
    fig_path = os.path.join(os.path.dirname(__file__) or ".",
                            "fig_A3_clifford_horizon.png")
    plt.savefig(fig_path, dpi=130, bbox_inches="tight"); plt.close()
    print(f"\nWrote {fig_path}")
    print(f"Wrote results.json key: A3_clifford_horizon")


if __name__ == "__main__":
    main()
